// ---------------------------------------------------------------------------
// Cache-bust versioning for thumbnail URLs.
//
// Thumbnail responses are served cacheable, so regenerated bytes are invisible
// until the URL changes — the webview (and, on the web client, the service
// worker) serves what it already has. Each path therefore carries a counter
// appended as `?v=`, bumped when its bytes change.
//
// The epoch is the same idea one level up: a wholesale rebuild has to change
// *every* URL, and walking every path to bump it individually would be both
// slow and unable to reach paths whose counters were already dropped. Adding
// the epoch to each counter shifts them all at once.
//
// Extracted from GalleryGrid / JustifiedGrid, where it was byte-identical.
// Only tier URLs go through this: JustifiedGrid's served-original cells use
// `mediaUrl(path, fit)`, which is deliberately cache-stable per (path, bucket)
// and already carries a query string.
// ---------------------------------------------------------------------------

export interface UrlVersions {
  /** `url` with this path's cache-bust suffix, or `url` unchanged at v0. */
  versioned(path: string, url: string): string;
  /** Point this path's next URL at fresh bytes. */
  bump(path: string): void;
  /** Forget one path's counter — it left the gallery. */
  forget(path: string): void;
  /** Shift every path's effective version at once (a rebuild). */
  bumpEpoch(): void;
  /**
   * Reset every counter, leaving the epoch alone. This does **not** guarantee
   * a fresh URL: at epoch 0 a path that was on `?v=3` goes back to the bare
   * URL, which the browser may still hold bytes for. It is only safe where the
   * URL is changing for another reason anyway — a tier change moves the tier
   * segment, so the old bytes are not reachable by the new URL. When the bytes
   * behind an unchanged URL have changed, pair it with `bumpEpoch()`.
   */
  clear(): void;
}

export function createUrlVersions(): UrlVersions {
  const versions = new Map<string, number>();
  let epoch = 0;

  return {
    versioned(path, url) {
      const v = (versions.get(path) ?? 0) + epoch;
      return v > 0 ? `${url}?v=${v}` : url;
    },
    bump(path) {
      versions.set(path, (versions.get(path) ?? 0) + 1);
    },
    forget(path) {
      versions.delete(path);
    },
    bumpEpoch() {
      epoch++;
    },
    clear() {
      versions.clear();
    },
  };
}
